IF NOT EXISTS (SELECT name FROM sys.databases WHERE name = 'master')
BEGIN
    CREATE DATABASE master;
END
GO

-- Seleciona o banco para uso
USE master;
GO


IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='PRODUTO' AND xtype='U')
BEGIN

    CREATE TABLE PRODUTO (
        CO_PRODUTO INT NOT NULL PRIMARY KEY,
        NO_PRODUTO VARCHAR(200) NOT NULL,
        PC_TAXA_JUROS NUMERIC(10, 9) NOT NULL,
        NU_MINIMO_MESES SMALLINT NOT NULL,
        NU_MAXIMO_MESES SMALLINT NULL,
        VR_MINIMO NUMERIC(18, 2) NOT NULL,
        VR_MAXIMO NUMERIC(18, 2) NULL
    );

INSERT INTO PRODUTO (CO_PRODUTO, NO_PRODUTO, PC_TAXA_JUROS, NU_MINIMO_MESES, NU_MAXIMO_MESES, VR_MINIMO, VR_MAXIMO)
VALUES (1, 'Produto 1', 0.017900000, 0, 24, 200.00, 10000.00);

INSERT INTO PRODUTO (CO_PRODUTO, NO_PRODUTO, PC_TAXA_JUROS, NU_MINIMO_MESES, NU_MAXIMO_MESES, VR_MINIMO, VR_MAXIMO)
VALUES (2, 'Produto 2', 0.017500000, 25, 48, 10001.00, 100000.00);

INSERT INTO PRODUTO (CO_PRODUTO, NO_PRODUTO, PC_TAXA_JUROS, NU_MINIMO_MESES, NU_MAXIMO_MESES, VR_MINIMO, VR_MAXIMO)
VALUES (3, 'Produto 3', 0.018200000, 49, 96, 100000.01, 1000000.00);

INSERT INTO PRODUTO (CO_PRODUTO, NO_PRODUTO, PC_TAXA_JUROS, NU_MINIMO_MESES, NU_MAXIMO_MESES, VR_MINIMO, VR_MAXIMO)
VALUES (4, 'Produto 4', 0.015100000, 96, NULL, 1000000.01, NULL);

END
GO

IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='SIMULACAO' AND xtype='U')
BEGIN
    CREATE TABLE SIMULACAO (
        ID_SIMULACAO INT IDENTITY(1,1) PRIMARY KEY,
        DATA_CRIACAO DATETIME NOT NULL DEFAULT GETDATE(),
        NUM_MESES INT NOT NULL,
        CO_PRODUTO INT NOT NULL FOREIGN KEY REFERENCES PRODUTO(CO_PRODUTO),
        PC_TAXA_JU NUMERIC(10, 9) NOT NULL,
        VR_SOLICITADO NUMERIC(18, 2) NOT NULL
    );
END
GO

IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='PARCELA' AND xtype='U')
BEGIN
    CREATE TABLE PARCELA (
        ID_PARCELA INT IDENTITY(1,1) PRIMARY KEY,
        ID_SIMULACAO INT NOT NULL FOREIGN KEY REFERENCES SIMULACAO(ID_SIMULACAO),
        TP_SISTEMA VARCHAR(10) NOT NULL,
        NU_PARCELA INT NOT NULL,
        VR_AMORTIZACAO NUMERIC(18, 2) NOT NULL,
        VR_JUROS NUMERIC(18, 2) NOT NULL,
        VR_PRESTACAO NUMERIC(18, 2) NOT NULL
    );
END
GO
